### ISSUE TITLE
网络连接错误

### ISSUE THREAD

**Issue by biglonglong** [XayahSuSuSu/Android-HNUDiscreteMathematicsHelper#2]
完成题目后提交，显示网络连接错误，导致无法提交

**Comment by Mightlaus** [comment]
确实，之前版本好像是可以重复提交覆盖原成绩的，现在还可以吗？很需要这个功能😭

**Comment by XayahSuSuSu** [comment]
很抱歉，目前我的账号已经无法获取题目，无法进一步定位问题 :(

**Comment by biglonglong** [comment]
202004060427 hnuysh&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月2日(星期四) 晚上11:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XayahSuSuSu/Android-HNUDiscreteMathematicsHelper] 网络连接错误 (Issue #2)





 
很抱歉，目前我的账号已经无法获取题目，无法进一步定位问题 :(

**Comment by XayahSuSuSu** [comment]
已修复

**Comment by ydyhello** [comment]
> 已修复

现在完成题目后，仍然显示网络连接错误👀
